apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ikie
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ikie
    app.kubernetes.io/part-of: tkrw-pr714-0075-0034-app
  name: devfile-sample-ikie
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ikie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ikie
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0034-tenant/tkrw-pr714-0075-0034-app/devfile-sample-ikie@sha256:6968228ff00ac53b18006c2db9240214ddcffac48b3e178a3f5104693c8e9b3a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
